### ISSUE TITLE
AssertionError Protocol mismatch

### ISSUE THREAD

**Issue by Hyllesen** [b4dnewz/robots-parse#1]
When I try to execute the example I get a assertion error:

```
const robotsParse = require("robots-parse");

robotsParse("https://sfbay.craigslist.org", (err, res) => {
  console.log("Result:", res);
});

```

```
node index.js
(node:16772) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: protocol mismatch
    at Object.wrappedProtocol.request (C:\nodeprojects\robot-parser\node_modules\follow-redirects\index.js:394:14)
    at Object.wrappedProtocol.get (C:\nodeprojects\robot-parser\node_modules\follow-redirects\index.js:401:37)
    at Promise (C:\nodeprojects\robot-parser\node_modules\robots-parse\lib\scanner.js:19:10)
    at new Promise (<anonymous>)
    at module.exports (C:\nodeprojects\robot-parser\node_modules\robots-parse\lib\scanner.js:9:10)
    at Object.<anonymous> (C:\nodeprojects\robot-parser\index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
(node:16772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
(rejection id: 1)
(node:16772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
node --version
v11.12.0
```

**Comment by b4dnewz** [comment]
Thanks for the tip, the new version just published __0.0.6__ should fix the issue, let me know if any problems still occurs and feel free to reopen the issue
